version: '3.9'

services:
  nginx:
    container_name: igfp-server
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    command: >
      sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\""
    volumes:
      - shared:/var/www/html
    networks:
      main:
        ipv4_address: 172.18.0.3

  php-fpm:
    container_name: igfp-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - shared:/var/www/html
    networks:
      main:
        ipv4_address: 172.18.0.2

volumes:
  shared:

networks:
  main:
    name: main
    ipam:
      config:
        - subnet: 172.18.0.3/16
